//! `theoremc` — a formal verification framework that compiles human-readable
//! `.theorem` files into proof harnesses.
//!
//! This crate is the public facade for theorem parsing, name mangling, and
//! build integration. Core theorem semantics live in `theoremc-core`, while
//! `theoremc-macros` owns proc-macro expansion.

/// Mangled-identifier collision detection across loaded theorem documents.
pub use theoremc_core::collision;

/// Action name mangling for deterministic, injective resolution.
pub use theoremc_core::mangle;

/// Schema types for `.theorem` document deserialization and validation.
pub use theoremc_core::schema;

/// The public proc macro that expands one crate-relative `.theorem` file.
pub use theoremc_macros::theorem_file;

/// Argument-expression lowering for proof harness code generation.
#[doc(hidden)]
pub(crate) mod arg_lowering;

/// Build-time theorem discovery shared with the Cargo build script.
#[cfg(test)]
#[doc(hidden)]
pub(crate) mod build_discovery;

/// Theorem suite generation for Cargo build integration.
#[cfg(test)]
#[doc(hidden)]
pub(crate) mod build_suite;

#[doc(hidden)]
mod __theoremc_generated_suite {
    //! Generated theorem suite integration.
    //!
    //! This hidden module bridges `OUT_DIR/theorem_suite.rs` into normal crate
    //! compilation. The generated suite keeps emitting bare
    //! `theorem_file!("...")` invocations; the imported proc macro now owns
    //! the stable per-file expansion behind that callsite.

    #[cfg(theoremc_has_theorems)]
    use theoremc_macros::theorem_file;

    // Include the generated suite file from OUT_DIR.
    // This file contains one `theorem_file!(...)` invocation per discovered
    // theorem path, generated by the build script.
    include!(concat!(env!("OUT_DIR"), "/theorem_suite.rs"));
}
