//! `theoremc` — a formal verification framework that compiles human-readable
//! `.theorem` files into proof harnesses.
//!
//! This crate provides the core library functionality for parsing, validating,
//! and processing theorem documents written in YAML.

/// Mangled-identifier collision detection across loaded theorem documents.
pub mod collision;

/// Action name mangling for deterministic, injective resolution.
pub mod mangle;

/// Schema types for `.theorem` document deserialization and validation.
pub mod schema;

/// Argument-expression lowering for proof harness code generation.
#[doc(hidden)]
pub(crate) mod arg_lowering;

/// Build-time theorem discovery shared with the Cargo build script.
#[cfg(test)]
#[doc(hidden)]
pub(crate) mod build_discovery;

/// Theorem suite generation for Cargo build integration.
#[cfg(test)]
#[doc(hidden)]
pub(crate) mod build_suite;

/// Generated theorem suite integration.
///
/// This hidden module provides the bridge between the generated
/// `OUT_DIR/theorem_suite.rs` and the crate's compilation. It defines a
/// temporary `theorem_file!` macro that expands to a compile-time
/// `include_str!` check, proving that discovered theorem paths are valid
/// crate-relative inputs.
///
/// Step 3.2 will replace this bridge with the real proc-macro-based
/// per-file expansion while keeping the same generated callsite.
#[doc(hidden)]
mod __theoremc_generated_suite {
    /// Temporary bridge macro for Step 3.1.2.
    ///
    /// This macro expands to a compile-time `include_str!` anchored at
    /// `CARGO_MANIFEST_DIR`, proving that the theorem file path is a valid
    /// crate-relative input. In Step 3.2, this will be replaced with real
    /// proc-macro-based per-file expansion.
    // This macro is used by the generated suite file when theorems exist.
    // When no theorems exist, the generated file is empty and this macro
    // is unused - this is expected behaviour.
    #[cfg_attr(
        not(any()),
        expect(
            unused_macros,
            reason = "macro is used by generated suite when theorems exist"
        )
    )]
    #[cfg_attr(
        any(),
        allow(
            unused_macros,
            reason = "macro is used by generated suite when theorems exist"
        )
    )]
    macro_rules! theorem_file {
        ($path:literal) => {
            const _: &str = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/", $path));
        };
    }

    // Include the generated suite file from OUT_DIR.
    // This file contains one `theorem_file!(...)` invocation per discovered
    // theorem path, generated by the build script in Step 3.1.2.
    include!(concat!(env!("OUT_DIR"), "/theorem_suite.rs"));
}
